### ISSUE TITLE
bin/release outputs garbage which Heroku used to ignore but now craps out on

### ISSUE THREAD

**Issue by afn** [AnyFetch/heroku-buildpack-tesseract#3]
Using this buildpack now results in the following error message during deployment:

```
remote:  !     Push failed: failed to read buildpack metadata: string not matched
remote:  !     Please try pushing again.
remote:  !     If the problem persists, see http://help.heroku.com/ and provide Request ID e6a4b3b6-278e-4ab1-b113-a7187dc5b683.
```

This is because `bin/release` is supposed to output [YAML](https://devcenter.heroku.com/articles/buildpack-api#bin-release) but it just outputs the line `release`. The script can safely be omitted.

**Comment by Amoki** [comment]
Thanks !
